[theme]
primaryColor = "#16798b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f7f8"
textColor = "#20394c"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
